JWT_SECRET: glaemfwldksgdkrjclstptkddpEnldjemsrjsskslRkdkadhzp-20250730!

# 서비스 URL들 (로컬 개발용)
AUTH_SERVICE_URL: http://localhost:8002
SHOP_SERVICE_URL: http://localhost:8006
FEEDBACK_SERVICE_URL: http://localhost:8003
BANNER_SERVICE_URL: http://localhost:8004