spring:
  config:
    import: application-secret.yml
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: shop
          uri: ${SHOP_SERVICE_URL:http://fanda-shop-service.fanda-be-shop.svc.cluster.local:8006}
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1
        - id: banner-reports
          uri: ${BANNER_SERVICE_URL:http://fanda-banner-service.fanda-be-marketing.svc.cluster.local:8004}
          predicates:
            - Path=/banner/api/v1/reports/**
          filters:
            - StripPrefix=1
        - id: banner-others
          uri: ${BANNER_SERVICE_URL:http://fanda-banner-service.fanda-be-marketing.svc.cluster.local:8004}
          predicates:
            - Path=/banner/api/v1/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: ${AUTH_SERVICE_URL:http://fanda-auth-service.fanda-be-auth.svc.cluster.local:8002}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: feedback-admin
          uri: ${FEEDBACK_SERVICE_URL:http://fanda-feedback-service.fanda-be-marketing.svc.cluster.local:8003}
          predicates:
            - Path=/feedback/api/v1/admin/**
          filters:
            - StripPrefix=1
        - id: feedback-others
          uri: ${FEEDBACK_SERVICE_URL:http://fanda-feedback-service.fanda-be-marketing.svc.cluster.local:8003}
          predicates:
            - Path=/feedback/api/v1/**
          filters:
            - StripPrefix=1
jwt:
  secret: ${JWT_SECRET}

server:
  port: 8001