DB_HOST: mysql.fanda-db-ms.svc.cluster.local
DB_USERNAME: root
DB_PASSWORD: rootpass

# AWS 설정
AWS_ACCESS_KEY_ID: YOUR_AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN: YOUR_AWS_SESSION_TOKEN
AWS_REGION: us-east-1

# Kafka 설정
SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.fanda-kafka.svc.cluster.local:9092

# JPA 설정
JPA_DDL_AUTO: update