etl:
  base-url: http://k8s-fandabee-fandaetl-d06eb86c05-f995576d72679abd.elb.us-east-1.amazonaws.com:5000

personalize:
  s3:
    bucket: fanda-bucket-aws9-3
    base-prefix: personalize

DB_HOST: mysql.fanda-db-ms.svc.cluster.local
DB_USERNAME: root
DB_PASSWORD: rootpass