spring:
  config:
    import: application-secret.yml
  application:
    name: recommend
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/recommend_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8005

etl:
  base-url: ${ETL_BASE_URL:${etl.base-url:http://k8s-fandabee-fandaetl-d06eb86c05-f995576d72679abd.elb.us-east-1.amazonaws.com:5000}}
  connect-timeout-millis: 10000
  read-timeout-millis: 600000

personalize:
  region: us-east-1
  importRoleArn: arn:aws:iam::746491138596:role/fanda-Personalized-access

  datasetGroupName: fanda-dsg
  datasetNames:
    interactions: fanda-interactions-dataset
    users: fanda-users-dataset
    items: fanda-items-dataset
  solutionName: fanda-solution
  recipeArn: arn:aws:personalize:::recipe/aws-user-personalization
  campaignName: fanda-campaign
  minProvisionedTPS: 1
  s3:
    bucket: ${AWS_S3_BUCKET}
    base-prefix: personalize

#management:
#  tracing:
#    sampling.probability: 1.0
#  otlp:
#    tracing:
#      endpoint: ${OTLP_HTTP_ENDPOINT:http://otel-collector.fanda-monitoring.svc.cluster.local:4318/v1/traces}