etl:
  base-url: http://192.168.1.126:5000

personalize:
  s3:
    bucket: fanda-bucket-aws9-3
    base-prefix: personalize

DB_HOST: mysql.fanda-db-ms.svc.cluster.local
DB_USERNAME: root
DB_PASSWORD: rootpass