
# Feedback Service Configuration
DB_HOST: mysql.fanda-db-ms.svc.cluster.local
DB_USERNAME: root
DB_PASSWORD: rootpass

# Kafka Configuration
SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.fanda-kafka.svc.cluster.local:9092