# Empty Spring Boot
DB_HOST: mysql.fanda-db-ms.svc.cluster.local
DB_USERNAME: root
DB_PASSWORD: rootpass

redis:
  host: localhost
  port: 6379

jwt:
  secret: glaemfwldksgdkrjclstptkddpEnldjemsrjsskslRkdkadhzp-20250730!
  token:
    access-expiration-time: 3600000
    refresh-expiration-time: 604800000