# AWS EKS 환경용 설정
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: 10000ms
      ssl:
        enabled: true

management:
  tracing:
    sampling.probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_HTTP_ENDPOINT:http://otel-collector.fanda-monitoring.svc.cluster.local:4318/v1/traces}