# Empty Spring Boot
#DB_HOST: mysql.fanda-db-ms.svc.cluster.local
#DB_USERNAME: root
#DB_PASSWORD: rootpass
DB_HOST: localhost
DB_USERNAME: root
DB_PASSWORD: again443

#redis:
#  host: redis-master.fanda-redis.svc.cluster.local
#  port: 6379

REDIS_HOST: redis-master.fanda-redis.svc.cluster.local
# REDIS_USERNAME: default
REDIS_PORT: 6379
REDIS_PASSWORD: fanda123!

jwt:
  secret: glaemfwldksgdkrjclstptkddpEnldjemsrjsskslRkdkadhzp-20250730!
  token:
    access-expiration-time: 3600000
    refresh-expiration-time: 604800000