apiVersion: v1
kind: Service
metadata:
  name: fanda-auth-service
  namespace: fanda-be-auth
  labels:
    app: fanda-auth
    service: auth
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30803  # Auth Service용 NodePort
      protocol: TCP
      name: http
  selector:
    app: fanda-auth