
apiVersion: v1
kind: Service
metadata:
  name: fanda-banner-service
  namespace: fanda-be-marketing
#  namespace: default
  labels:
    app: fanda-banner
    service: banner
spec:
  type: NodePort
  ports:
    - port: 8004
      targetPort: 8004
      nodePort: 30804  # Banner Service용 NodePort
      protocol: TCP
      name: http
  selector:
    app: fanda-banner