apiVersion: v1
kind: Secret
metadata:
  name: fanda-shop-secret
  namespace: fanda-be-shop
  labels:
    app: fanda-shop
    component: backend
    service: shop
type: Opaque
stringData:
  # MySQL root 계정 (root / rootpass)
  DB_ROOT_USERNAME: "root"
  DB_ROOT_PASSWORD: "rootpass"

  # MySQL fandauser 계정 (fandauser / fandapass)
  DB_USER_USERNAME: "fandauser"
  DB_USER_PASSWORD: "fandapass"