apiVersion: v1
kind: Service
metadata:
  name: fanda-shop-service
  namespace: fanda-be-shop
spec:
  type: NodePort
  ports:
    - name: http
      port: 8006
      targetPort: 8006
      nodePort: 30806
      protocol: TCP
  selector:
    app: fanda-shop
